spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_lab?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Fuckpenisex3258!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

logging:
  level:
    com.pattern.springlab: DEBUG
    org.hibernate.SQL: DEBUG